apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-app-set
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: dr-state
                    operator: In
                    values:
                      - active
                      - passive
          - git:
              repoURL: https://github.com/rmgrimm/example-argocd-dr-cluster-labels.git
              revision: main
              directories:
                - path: manifests/workloads/overlays/*
  template:
    metadata:
      name: 'workload-{{.path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rmgrimm/example-argocd-dr-cluster-labels.git
        targetRevision: main
        path: '{{.path.path}}'

        kustomize:
          components:
            - '../../components/dr-{{index .metadata.labels "dr-state"}}'
      destination:
        server: '{{.server}}'
        namespace: workloads
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true

