apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - pairs:
      dr-state: passive

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: patch-deployment.yaml
