apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml

replacements:
  - source:
      group: ''
      version: v1
      kind: ConfigMap
    targets:
      - select:
          group: apps
          version: v1
          kind: Deployment
        fieldPaths:
          - metadata.name
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
